project_id = "sltxwkdvaapyeosikegj"

[functions.push-notifications]
verify_jwt = false

[functions.validate-serial]
verify_jwt = false

[functions.create-serial]
verify_jwt = false

[functions.monitor-heartbeat]
verify_jwt = false

[functions.translate-i18n]
verify_jwt = false